fmod FIELD is
	protecting NAT .
	sort Field .
	ops id typ dst pt sw : -> Field [ctor] .
	ops SSH UDP TCP : -> Nat [ctor] .
	op undef : -> Nat [ctor] .
endfm

fmod PREDICATE is	
	protecting FIELD .
	protecting NAT .

	sort Predicate .

	op one : -> Predicate [ctor] .
	op zero : -> Predicate [ctor] .	

	op _=_ : Field Nat -> Predicate [ctor metadata "test" prec 39] .
	op ~_ : Predicate -> Predicate [ctor metadata "negation" prec 38] .
endfm

fmod POLICY is
	protecting FIELD .
	protecting NAT .
	protecting PREDICATE .

	sort Policy .
	subsort Predicate < Policy .

	op _+_ : Policy Policy -> Policy [ctor comm assoc metadata "nondeterministic choice" prec 43 gather (E e)] .
	op _._ : Policy Policy -> Policy [ctor assoc metadata "sequencing" prec 40] .
	op _;_ : Policy Policy -> Policy [ctor metadata "sequential composition" prec 40] .
	op _<-_ : Field Nat -> Policy [ctor metadata "modification" prec 39] .
	op _||_ : Policy Policy -> Policy [ctor assoc metadata "parallel composition" prec 42 gather (E e)] .
endfm

fmod COMM is
	protecting POLICY .

	sort Channel .

	op _?_ : Channel Policy -> Policy .
	op _!_ : Channel Policy -> Policy .
endfm

fmod RECURSIVE is
	protecting POLICY .

	sort Recursive .
	subsort Recursive < Policy .
endfm

view Policy from TRIV to POLICY is
	sort Elt to Policy .
endv

fmod VARIABLE-DECLARATIONS is
	protecting COMM .
	protecting RECURSIVE .

    ops upS1 upS2 upS3 upS4 upS5 upS6 : -> Channel .
    ops Switch1v1 Switch1v2 Switch2v1 Switch2v2 Switch3v1 Switch3v2 Switch4v1 Switch4v2 Switch5v1 Switch5v2 Switch5v3 Switch6v1 Switch6v2 Switch6v3 recL : -> Recursive .
endfm

mod MAUDE2SPIN-FIRST-STEP is
	protecting VARIABLE-DECLARATIONS .
	protecting FIELD .
    protecting POLICY .
    protecting COMM .
    protecting RECURSIVE .

    sort Parser . 
    subsort Parser < Channel .
    subsort Parser < Policy .
    subsort Parser < Field .

    op @Recursive<_> : Recursive -> Parser [frozen strat(0)] .
	op @Send<_,_> : Channel Policy -> Parser [frozen strat(0)] .
	op @Receive<_,_> : Channel Policy -> Parser [frozen strat(0)] .

	var X : Channel .
	var R : Recursive .
	var P : Policy .

    eq X ! P = @Send< X, P > .
	eq X ? P = @Receive< X, P > .
    eq R = @Recursive< R > .
endm

mod MAUDE2SPIN-SECOND-STEP is
	protecting FIELD .
	protecting PREDICATE .
    protecting POLICY .
    protecting COMM .
    protecting RECURSIVE .
	protecting MAUDE2SPIN-FIRST-STEP .

	protecting LIST {Policy} * (sort List {Policy} to ListPolicy, op __ to _:-_) .


	var LP LP' : ListPolicy .
	var P Q : Policy .


	op ifBlock[_] : ListPolicy -> ListPolicy .
	op sequence[_] : ListPolicy -> ListPolicy .

	op _:if:_ : ListPolicy ListPolicy -> ListPolicy .
	op _:seq:_ : ListPolicy ListPolicy -> ListPolicy .


	eq [if-1] : P + Q = ifBlock[P :if: Q] .
	eq [if-2] : P + ifBlock[LP] = ifBlock[P :if: LP] . 
	eq [if-3] : P + sequence[LP] = ifBlock[P :if: sequence[LP]] .
	eq [if-4] : LP + ifBlock[LP'] = ifBlock[LP :if: LP'] .
	eq [if-5] : sequence[LP] + sequence[LP'] = ifBlock[sequence[LP] :if: sequence[LP']] .
	

	eq [seq-1] : P . Q = sequence[P :seq: Q] .
	eq [seq-2] : P . sequence[LP] = sequence[P :seq: LP] .
	eq [seq-3] : LP . sequence[LP'] = sequence[LP :seq: LP'] .
endm

