fmod LABEL is
	sort Label .
	sort LabelEl .
endfm

fmod ENV is	
	protecting LABEL .

	sort Env .
	subsort Env < LabelEl .
	
	op pre-env : -> Env .
	op pol-env : -> Env .
endfm

fmod FIELD is
	protecting NAT .
	sort Field .
	ops id typ dst pt sw : -> Field [ctor] .
	ops SSH UDP TCP : -> Nat [ctor] .
	op undef : -> Nat [ctor] .
endfm

fmod PACKET is
	protecting NAT .
	protecting FIELD .	
	protecting LABEL .	
	sort Packet .
	sort Value . 
	

	subsort Packet < LabelEl .


	op (_,_) : Field Nat -> Value [ctor] .
	
	op top(_) : Packet -> Packet [ctor] .
	op bottom(_) : Packet -> Packet [ctor] .	

	op #(id : _, typ : _, dst : _, pt : _, sw : _) : Nat Nat Nat Nat Nat -> Packet [ctor] .
	op _$_ : Packet Field -> Nat [ctor] .
	op _:=_ : Packet Value -> Packet [ctor] .	

	vars N1 N2 N3 N4 N5 V : Nat .
	var F : Field .
	var P P1 P2 : Packet .

	eq bottom(bottom(P)) = bottom(P) .
	eq top(top(P)) = top(P) .


	eq #(id : N1, typ : N2, dst : N3, pt : N4, sw : N5) $ id = N1 .
	eq #(id : N1, typ : N2, dst : N3, pt : N4, sw : N5) $ typ = N2 .
	eq #(id : N1, typ : N2, dst : N3, pt : N4, sw : N5) $ dst = N3 .
	eq #(id : N1, typ : N2, dst : N3, pt : N4, sw : N5) $ pt = N4 .
	eq #(id : N1, typ : N2, dst : N3, pt : N4, sw : N5) $ sw = N5 .
	eq #(id : N1, typ : N2, dst : N3, pt : N4, sw : N5) $ F = undef [owise] .

	eq #(id : N1, typ : N2, dst : N3, pt : N4, sw : N5) := (id, V) = #(id : V, typ : N2, dst : N3, pt : N4, sw : N5) .
	eq #(id : N1, typ : N2, dst : N3, pt : N4, sw : N5) := (typ, V) = #(id : N1, typ : V, dst : N3, pt : N4, sw : N5) .
	eq #(id : N1, typ : N2, dst : N3, pt : N4, sw : N5) := (dst, V) = #(id : N1, typ : N2, dst : V, pt : N4, sw : N5) .
	eq #(id : N1, typ : N2, dst : N3, pt : N4, sw : N5) := (pt, V) = #(id : N1, typ : N2, dst : N3, pt : V, sw : N5) .
	eq #(id : N1, typ : N2, dst : N3, pt : N4, sw : N5) := (sw, V) = #(id : N1, typ : N2, dst : N3, pt : N4, sw : V) .
	eq #(id : N1, typ : N2, dst : N3, pt : N4, sw : N5) := (F, V) = #(id : N1, typ : N2, dst : N3, pt : N4, sw : N5) [owise] .
endfm

fmod PREDICATE is	
	protecting FIELD .
	protecting NAT .

	sort Predicate .

	op one : -> Predicate [ctor] .
	op zero : -> Predicate [ctor] .	

	op _=_ : Field Nat -> Predicate [ctor metadata "test" prec 39] .
	op ~_ : Predicate -> Predicate [ctor metadata "negation" prec 38] .
endfm

fmod POLICY is
	protecting FIELD .
	protecting NAT .
	protecting PREDICATE .

	sort Policy .
	subsort Predicate < Policy .

	op _+_ : Policy Policy -> Policy [ctor metadata "nondeterministic choice" prec 43 gather (E e)] .
	op _._ : Policy Policy -> Policy [ctor metadata "sequencing" prec 40] .
	op _;_ : Policy Policy -> Policy [ctor metadata "sequential composition" prec 40] .
	op _<-_ : Field Nat -> Policy [ctor metadata "modification" prec 39] .
	op _||_ : Policy Policy -> Policy [ctor metadata "parallel composition" prec 42 gather (E e)] .
endfm

view Policy from TRIV to POLICY is
	sort Elt to Policy .
endv

mod COMM is
	protecting LABEL .
	protecting POLICY .
	protecting MAP {Policy, Bool} * (sort Map {Policy, Bool} to ChannelDict, op empty to emptyChMap) . --- op _,_ to combineMap) .

	sort Channel .

	op _:_ : Nat ChannelDict -> Channel .

	op _?_ : Channel Policy -> Policy .
	op _!_ : Channel Policy -> Policy .

	op readAvailable(_,_) : ChannelDict Policy -> Bool .
	op consume(_,_) : ChannelDict Policy -> ChannelDict .
	op send(_,_) : ChannelDict Policy -> ChannelDict .
endm

view ChannelDict from TRIV to COMM is
	sort Elt to ChannelDict .
endv

mod COMM-DEF is
	protecting LABEL .
	protecting POLICY .
	protecting COMM .
	protecting MAP {Nat, ChannelDict} * (sort Map {Nat, ChannelDict} to Comm, op empty to emptyCoMap) .
	
	subsort Comm < LabelEl .

	var P : Policy .
	var X : ChannelDict .
	var C : Comm .
	var I : Nat .

	op getChannel(_,_) : Comm Nat -> ChannelDict .
	op setChannel(_,_,_) : Comm Nat ChannelDict -> Comm .

	eq getChannel(C, I) = C[I] .
	eq setChannel(C, I, X) = insert(I, X, C) .

	eq send(X, P) = insert(P, true, X) .
	ceq consume(X, P) = insert(P, false, X) if X[P] == true .
	ceq readAvailable(X, P) = true if X[P] == true .
	eq readAvailable(X, P) = false [owise] .
endm

fmod NEW is
	protecting LABEL .

	sort New .

	subsort New < LabelEl .

	op new(_) : LabelEl -> New .
endfm

fmod RCFG is
	protecting LABEL .
	protecting POLICY .

	sort Rcfg .

	subsort Rcfg < LabelEl .

	op rcfg(_) : Policy -> Rcfg .
endfm

mod LABEL-DEF is
	protecting LABEL .
	protecting ENV .
	protecting PACKET .
	protecting COMM .
	protecting COMM-DEF .
	protecting NEW .
	protecting RCFG .

	sort Template .
	---protecting MAP {Nat, Channel} * (op empty to emptyCoMap) .

	op _x_x_x_x_ : Env Packet Comm New Rcfg -> Template .
	op [_] : Template -> Label .

	var E1 E2 : Env .
	var P1 P2 : Packet .
	var C1 C2 : Comm .
	var N1 N2 : New .	
	var R1 R2 : Rcfg .	

	op getEnv(_) : Label -> Env .
	op setEnv(_,_) : Label Env -> Label .
	eq getEnv([E1 x P1 x C1 x N1 x R1]) = E1 . 
	eq setEnv([E1 x P1 x C1 x N1 x R1], E2) = [E2 x P1 x C1 x N1 x R1] .

	op getPacket(_) : Label -> Packet .
	op setPacket(_,_) : Label Packet -> Label .
	eq getPacket([E1 x P1 x C1 x N1 x R1]) = P1 . 
	eq setPacket([E1 x P1 x C1 x N1 x R1], P2) = [E1 x P2 x C1 x N1 x R1] .

	op getComm(_) : Label -> Comm .
	op setComm(_,_) : Label Comm -> Label .
	eq getComm([E1 x P1 x C1 x N1 x R1]) = C1 . 
	eq setComm([E1 x P1 x C1 x N1 x R1], C2) = [E1 x P1 x C2 x N1 x R1] .

	op getNew(_) : Label -> LabelEl .
	op setNew(_,_) : Label LabelEl -> Label .
	eq getNew([E1 x P1 x C1 x N1 x R1]) = N1 . 
	eq setNew([E1 x P1 x C1 x N1 x R1], N2) = [E1 x P1 x C1 x N2 x R1] .

	op getRcfg(_) : Label -> Comm .
	op setRcfg(_,_) : Label Comm -> Label .
	eq getRcfg([E1 x P1 x C1 x N1 x R1]) = R1 . 
	eq setRcfg([E1 x P1 x C1 x N1 x R1], R2) = [E1 x P1 x C1 x N1 x R2] .
endm

fmod TERMINATE is 
	protecting PREDICATE .
	protecting POLICY .
	sort Terminate .
	subsort Terminate < Predicate .
	subsort Terminate < Policy .
	op pre-terminate : -> Terminate [ctor] .
	op pol-terminate : -> Terminate [ctor] .
endfm

mod DNA is
	protecting ENV .
	protecting LABEL .
	protecting FIELD .
	protecting PACKET .
	protecting COMM .
	protecting COMM-DEF .
	protecting NAT .
	protecting PREDICATE .
	protecting POLICY .
	protecting LABEL-DEF .	
	protecting TERMINATE .

	sort Configuration .

	op <_,_> : Predicate Label -> Configuration .
	op <_,_> : Policy Label -> Configuration .
	
	sort Recursive .
	subsort Recursive < Policy .

	op _.=_ : Recursive Policy -> Recursive .
	
		
	---Predicate implementation
	vars A B : Predicate .
	var F : Field .
	var N : Nat .
	var L L' : Label .
	var Sigma' : Packet .
	var Alpha : LabelEl .
	var C : Comm .
	var P P' P'' Q Q' Q'' : Policy .
	var X : ChannelDict .
	var RN : Recursive .


	---fig 5 line 1
	rl [zero] : < zero, L > => < pre-terminate, setPacket(L, bottom(getPacket(L))) > .
	rl [one] : < one, L > => < pre-terminate, setPacket(L, top(getPacket(L))) > .




	---fig 5 line 2
	crl [test-top] : < F = N , L > => < pre-terminate, setPacket(L, top(getPacket(L))) > if (getPacket(L) $ F) == N .
	crl [test-bottom] : < F = N , L > => < pre-terminate, setPacket(L, bottom(getPacket(L))) > if (getPacket(L) $ F) =/= N .




	---fig 5 line 3
	crl [neg-top] : (< ~ A, L >) => < pre-terminate, setPacket(L, top(getPacket(L))) > if (< A, L >) => (< pre-terminate, setPacket(L, bottom(getPacket(L))) >) . 
	crl [neg-bottom] : (< ~ A, L >) => < pre-terminate, setPacket(L, bottom(getPacket(L))) > if (< A, L >) => (< pre-terminate, setPacket(L, top(getPacket(L))) >) .




	---fig 5 line 4
	crl [pre-plus-left-top] : (< A + B, L >) => < pre-terminate, setPacket(L, top(getPacket(L))) > if (< A, L >) => (< pre-terminate, setPacket(L, top(getPacket(L))) >) . 
	crl [pre-plus-right-top] : (< A + B, L >) => < pre-terminate, setPacket(L, top(getPacket(L))) > if (< B, L >) => (< pre-terminate, setPacket(L, top(getPacket(L))) >) . 
	
	


	---fig 5 line 5
	crl [pre-plus-bottom] : (< A + B, L >) => < pre-terminate, setPacket(L, bottom(getPacket(L))) > if (< A, L >) => (< pre-terminate, setPacket(L, bottom(getPacket(L))) >) /\ (< B, L >) => (< pre-terminate, setPacket(L, bottom(getPacket(L))) >) . 



	---fig 5 line 6
	crl [pre-dot-top] : (< A . B, L >) => (< pre-terminate, setPacket(L, top(getPacket(L))) >) if (< A, L >) => (< pre-terminate, setPacket(L, top(getPacket(L))) >) /\ (< B, L >) => (< pre-terminate, setPacket(L, top(getPacket(L))) >) .
 	
	 


	---fig 5 line 7 
	crl [pre-dot-left-bottom] : (< A . B, L >) => (< pre-terminate, setPacket(L, bottom(getPacket(L))) >) if (< A, L >) => (< pre-terminate, setPacket(L, bottom(getPacket(L))) >) .
	crl [pre-dot-right-bottom] : (< A . B, L >) => (< pre-terminate, setPacket(L, bottom(getPacket(L))) >) if (< B, L >) => (< pre-terminate, setPacket(L, bottom(getPacket(L))) >) .






	---fig 6 line 1
	---this causes non-termination
	---not exactly sure what is the use of this
	---crl [pre-pol-top] : (< A, L >) => (< pol-terminate, setPacket(L, top(getPacket(L))) >) if (< A, L >) => (< pre-terminate, setPacket(L, top(getPacket(L))) >) .
	---crl [pre-pol-bottom] : (< A, L >) => (< pol-terminate, setPacket(L, bottom(getPacket(L))) >) if getPacket(L) == bottom(getPacket(L)) .
	crl [pre-pol] : (< pre-terminate, L >) => (< pol-terminate, L >) if getPacket(L) =/= bottom(getPacket(L)) .



	---fig 6 line 2
 	crl [assgn-top] : (< F <- N, L >) => < pol-terminate, setPacket(L, (getPacket(L) := (F, N))) > if getPacket(L) =/= bottom(getPacket(L)) . 
	crl [assgn-bottom] : (< F <- N, L >) => < pol-terminate, L > if getPacket(L) == bottom(getPacket(L)) .




	---fig 6 line 3
	crl [pol-dot] : (< P . Q, L >) => (< P' . Q, L' >) if (< P, L >) => (< P', L' >) /\ P' =/= P .
	crl [pol-dot-packet-top-terminate] : (< P . Q, L >) => (< Q, L' >) if (< P, L >) => (< pol-terminate, setPacket(L', top(getPacket(L'))) >) .
	crl [pol-dot-packet-bottom-terminate] : (< P . Q, L >) => (< Q, setPacket(L', bottom(getPacket(L'))) >) if (< P, L >) => (< pol-terminate, setPacket(L', bottom(getPacket(L'))) >) .
	
	--- [pol-dot-non-bottom-terminate] is needed since due to [pol-dot] we might encounter < pol-terminate . Q, L > where getPacket(L) is top
	--- in that case, according to fig 6 row 3, column 2, we could get < Q, L >. Therefore, we explicitly need to encode [pol-dot-non-bottom-terminate].
	crl [pol-dot-non-bottom-terminate] : (< pol-terminate . Q, L >) => (< Q, L >) if getPacket(L) =/= bottom(getPacket(L)) .
	crl [pre-dot-non-bottom-terminate] : (< pre-terminate . Q, L >) => (< Q, L >) if getPacket(L) =/= bottom(getPacket(L)) .
	


	---fig 6 line 4
	crl [pol-dot-receive-terminate] : (< P . Q, L >) => (< Q, setComm(L, setChannel(getComm(L), N, consume(X, P))) >) if (< P, L >) => (< pol-terminate, setComm(L, setChannel(getComm(L), N, consume(X, P))) >) .
	crl [pol-dot-send-terminate] : (< P . Q, L >) => (< Q, setComm(L, setChannel(getComm(L), N, send(X, P))) >) if (< P, L >) => (< pol-terminate, setComm(L, setChannel(getComm(L), N, send(X, P))) >) .
	---crl [pol-dot-rcfg-terminate] : (< P . Q, L >) => (< Q, setRcfg(L, rcfg(P')) >) if (< P, L >) => (< pol-terminate, setRcfg(L, rcfg(P')) >) .




	---fig 6 line 5
	crl [pol-plus-left] : (< P + Q, L >) => (< P', L' >) if (< P, L >) => (< P', L' >) /\ P' =/= P .
	crl [pol-plus-right] : (< P + Q, L >) => (< Q', L' >) if (< Q, L >) => (< Q', L' >) /\ Q' =/= Q .
	crl [pol-plus-left-terminate] : (< P + Q, L >) => (< pol-terminate, L' >) if (< P, L >) => (< pol-terminate, L' >) .




	---fig 6 line 6
	crl [pol-plus-right-terminate] : (< P + Q, L >) => (< P, L' >) if (< Q, L >) => (< pol-terminate, L' >) .
	crl [recursive] : (< RN .= P, L >) => (< P', L' >) if (< P, L >) => (< P', L' >) /\ P' =/= P .
	crl [recursive-terminate] : (< RN .= P, L >) => (< pol-terminate, L' >) if (< P, L >) => (< pol-terminate, L' >) .





	---fig 7, line 1
	crl [pol-seq] : (< P ; Q, L >) => (< P' ; Q, L' >) if (< P, L >) => (< P', L' >) /\ P' =/= P .
	---how to define col 2?




	---fig 7, line 2
	crl [in] : < (N : X) ? P, L > => < P, setComm(L, setChannel(getComm(L), N, consume(X, P))) > if readAvailable(getComm(L)[N], P) == true .
	rl [out] : < (N : X) ! P, L > => < pol-terminate, setComm(L, setChannel(getComm(L), N, send(X, P))) > .




	---fig7 line 3
	crl [pol-synch-left] : (< P || Q, L >) => (< P' || Q, L' >) if (< P, L >) => (< P', L' >) /\ P' =/= P .
	crl [pol-synch-right] : (< P || Q, L >) => (< P || Q', L' >) if (< Q, L >) => (< Q', L' >) /\ Q' =/= Q .




	---fig 7 line 4
	crl [pol-synch-packet-left-terminate-top] : (< P || Q, L >) => (< Q, setPacket(L, Sigma') >) if (< P, L >) => (< pol-terminate, setPacket(L, top(Sigma')) >) .
	crl [pol-synch-packet-left-terminate-bottom] : (< P || Q, L >) => (< Q, setPacket(L, bottom(Sigma')) >) if (< P, L >) => (< pol-terminate, setPacket(L, bottom(Sigma')) >) .
	crl [pol-synch-packet-left-send] : (< P || Q, L >) => (< Q, setComm(L, setChannel(getComm(L), N, send(X, P''))) >) if (< P, L >) => (< pol-terminate, setComm(L, setChannel(getComm(L), N, send(X, P''))) >) .

	


	---fig 7 line 5
	crl [pol-synch-packet-right-terminate-top] : (< P || Q, L >) => (< P, setPacket(L, Sigma') >) if (< Q, L >) => (< pol-terminate, setPacket(L, top(Sigma')) >) .
	crl [pol-synch-packet-right-terminate-bottom] : (< P || Q, L >) => (< P, setPacket(L, bottom(Sigma')) >) if (< Q, L >) => (< pol-terminate, setPacket(L, bottom(Sigma')) >) .
	crl [pol-synch-packet-right-send] : (< P || Q, L >) => (< P, setComm(L, setChannel(getComm(L), N, send(X, P''))) >) if (< Q, L >) => (< pol-terminate, setComm(L, setChannel(getComm(L), N, send(X, P''))) >) .




	---fig 7 line 6
	---crl [rcfg-send-receive] : (< P || Q, L >) => (< P' || Q', setRcfg(L, rcfg(P'')) >) if (< P, L >) => (< P', setComm(L, X !Lab P'') >) /\ (< Q, L >) => (< Q', setComm(L, X ?Lab P'') >) .
	---crl [rcfg-send-terminate-receive] : (< P || Q, L >) => (< Q', setRcfg(L, rcfg(P'')) >) if (< P, L >) => (< pol-terminate, setComm(L, X !Lab P'') >) /\ (< Q, L >) => (< Q', setComm(L, X ?Lab P'') >) .




	---fig 7 line 7
	---crl [rcfg-receive-send] : (< P || Q, L >) => (< P' || Q', setRcfg(L, rcfg(P'')) >) if (< P, L >) => (< P', setComm(L, X ?Lab P'') >) /\ (< Q, L >) => (< Q', setComm(L, X !Lab P'') >) .
	---crl [rcfg-receive-send-terminate] : (< P || Q, L >) => (< P', setRcfg(L, rcfg(P'')) >) if (< P, L >) => (< P', setComm(L, X ?Lab P'') >) /\ (< Q, L >) => (< pol-terminate, setComm(L, X !Lab P'') >) .
endm


mod TEST1 is
	protecting DNA .

	var E : Env .
	var C : Comm .
	var X : ChannelDict .
	var Ne : New .
	var R : Rcfg .
	vars N1 N2 N3 N4 N5 : Nat .

	---rew in TEST1 : < ((1 : X) ! pt <- 2) . ((1 : X) ? pt <- 2), [E x #(id : N1,typ : N2,dst : N3,pt : 1,sw : N5) x insert(1, X, C) x Ne x R] > .
endm


mod TEST2 is
	protecting DNA .

	var upS1 upS2 : ChannelDict .
	var E E' : Env .
	var Co Co' : Comm .
	var X : ChannelDict .
	var Ne Ne' : New .
	var R R' : Rcfg .
	vars N1 N2 N3 N4 N5 N1' N2' N3' N4' N5' : Nat .
	var P P' : Policy .

	------rew in TEST2 : [E x #(id : N1, typ : N2, dst : N3, pt : N4, sw : N5) x insert(1, upS1, emptyCoMap), insert(2, upS2, emptyCoMap) x Ne x R] .
	---rew in TEST2 : < ((1 : upS1) ! pt <- 2) || (((1 : upS1) ? pt <- 2) . pt <- 3) || (((1 : upS1) ? pt <- 2) . pt <- 4), [E x #(id : N1, typ : N2, dst : N3, pt : N4, sw : N5) x insert(1, upS1, emptyCoMap), insert(2, upS2, emptyCoMap) x Ne x R] > .
	---search in TEST2 : < ((1 : upS1) ! pt <- 2) || (((1 : upS1) ? pt <- 2) . pt <- 3) || (((1 : upS1) ? pt <- 2) . pt <- 4), [E x #(id : N1, typ : N2, dst : N3, pt : N4, sw : N5) x insert(1, upS1, emptyCoMap), insert(2, upS2, emptyCoMap) x Ne x R] > =>* < P', [E' x #(id : N1', typ : N2', dst : N3', pt : 4, sw : N5') x Co' x Ne' x R'] > .
endm


mod DISTRIBUTED-CONTROLLER is
	protecting DNA .

	ops D L C1 C2 : -> Recursive .
	op Switch(_,_,_) : Nat Channel Policy -> Policy .

	var upS1 upS2 upS3 upS4 upS5 upS6 : ChannelDict .
	var E E' : Env .
	var Co Co' : Comm .
	var Ne Ne' : New .
	var R R' : Rcfg .
	vars N1 N2 N3 N4 N5 N1' N2' N3' N4' N5' : Nat .

	var N : Nat .
	var P : Policy .
	var C : Channel .
	var Lbl Lbl' : Label .
	---eq Switch(N, C, P) = P ; Switch(N, C, P) + ((C ? (pt = 2) . (pt <- 4)) ; Switch(N, C, (pt = 2) . (pt <- 4)) + (C ? (pt = 12) . (pt <- 14)) ; Switch(N, C, (pt = 12) . (pt <- 14)) + (C ? zero) ; Switch(N, C, zero) + (C ? (pt = 6) . (pt <- 7)) ; Switch(N, C, (pt = 6) . (pt <- 7)) + (C ? (pt = 8) . (pt <- 10)) ; Switch(N, C, (pt = 8) . (pt <- 10))) .


	rl [sw-1] : Switch(N, C, P) => P ; Switch(N, C, P) + (C ? (pt = 2) . (pt <- 4)) ; Switch(N, C, (pt = 2) . (pt <- 4)) .
	rl [sw-2] : Switch(N, C, P) => P ; Switch(N, C, P) + (C ? (pt = 12) . (pt <- 14)) ; Switch(N, C, (pt = 12) . (pt <- 14)) .
	rl [sw-3] : Switch(N, C, P) => P ; Switch(N, C, P) + (C ? zero) ; Switch(N, C, zero) .
	rl [sw-4] : Switch(N, C, P) => P ; Switch(N, C, P) + (C ? (pt = 6) . (pt <- 7)) ; Switch(N, C, (pt = 6) . (pt <- 7)) .
	rl [sw-5] : Switch(N, C, P) => P ; Switch(N, C, P) + (C ? (pt = 8) . (pt <- 10)) ; Switch(N, C, (pt = 8) . (pt <- 10)) .




	---D .= (Switch(1, 1 : upS1, pt = 2 . pt <- 4) || Switch(2, 2 : upS2, pt = 12 . pt <- 14) || Switch(3, 3 : upS3, zero) || Switch(4, 4 : upS4, zero) || Switch(5, 5 : upS5, pt = 6 . pt <- 7) || Switch(6, 6 : upS6, pt = 8 . pt <- 10)) . 

	---(L .= (((pt = 3) . (pt <- 5)) + ((pt = 4) . (pt <- 6)) + ((pt = 7) . (pt <- 8)) + ((pt = 9) . (pt <- 11)) + ((pt = 10) . (pt <- 12))) ; L)

	---C1 .= ((1 : upS1 ! zero) || (3 : upS3 ! (pt = 1 . pt <- 3)) || (5 : upS5 ! (pt = 5 . pt <- 7)))
	---C2 .= ((2 : upS2 ! zero) || (4 : upS4 ! (pt = 11 . pt <- 13)) || (6 : upS6 ! (pt = 8 . pt <- 9)))

	---SDN .= D || C1 || C2 || L
	
	---in_label .= [E x #(id : N1, typ : N2, dst : N3, pt : 1, sw : N5) x insert(1, upS1, emptyCoMap), insert(2, upS2, emptyCoMap), insert(3, upS3, emptyCoMap), insert(4, upS4, emptyCoMap), insert(5, upS6, emptyCoMap), insert(6, upS6, emptyCoMap) x Ne x R]
	---out_label .= [E' x #(id : N1', typ : N2', dst : N3', pt : 14, sw : N5') x Co' x Ne' x R']

	---search [, 3] < ((Switch(1, 1 : upS1, pt = 2 . pt <- 4) || Switch(2, 2 : upS2, pt = 12 . pt <- 14) || Switch(3, 3 : upS3, zero) || Switch(4, 4 : upS4, zero) || Switch(5, 5 : upS5, pt = 6 . pt <- 7) || Switch(6, 6 : upS6, pt = 8 . pt <- 10)) || ((1 : upS1 ! zero) || (3 : upS3 ! (pt = 1 . pt <- 3)) || (5 : upS5 ! (pt = 5 . pt <- 7))) || ((2 : upS2 ! zero) || (4 : upS4 ! (pt = 11 . pt <- 13)) || (6 : upS6 ! (pt = 8 . pt <- 9))) || (L .= (((pt = 3) . (pt <- 5)) + ((pt = 4) . (pt <- 6)) + ((pt = 7) . (pt <- 8)) + ((pt = 9) . (pt <- 11)) + ((pt = 10) . (pt <- 12))) ; L)), [E x #(id : N1, typ : N2, dst : N3, pt : 1, sw : N5) x insert(1, upS1, emptyCoMap), insert(2, upS2, emptyCoMap), insert(3, upS3, emptyCoMap), insert(4, upS4, emptyCoMap), insert(5, upS6, emptyCoMap), insert(6, upS6, emptyCoMap) x Ne x R] > =>* < P, [E' x #(id : N1', typ : N2', dst : N3', pt : 14, sw : N5') x Co' x Ne' x R'] > .

	---search < (1 : upS1 ! pt <- 2) . (1 : upS1 ? pt <- 2), [E x #(id : N1, typ : N2, dst : N3, pt : 1, sw : N5) x insert(1, upS1, emptyCoMap), insert(2, upS2, emptyCoMap) x Ne x R] > =>* < P:Policy, Lbl > .

	
endm

mod DISTRIBUTED-CONTROLLER2 is
	protecting DNA .

	ops D L C1 C2 : -> Recursive .
	op Switch(_,_,_) : Nat Channel Policy -> Policy .

	var upS1 upS2 upS3 upS4 upS5 upS6 : ChannelDict .
	var E E' : Env .
	var Co Co' : Comm .
	var Ne Ne' : New .
	var R R' : Rcfg .
	vars N1 N2 N3 N4 N5 N1' N2' N3' N4' N5' : Nat .

	var N : Nat .
	var P P' : Policy .
	var C : Channel .
	var Lbl Lbl' : Label .

	rl Switch(N, C, P) => P .
	---; Switch(N, C, P) + ((C ? (pt = 2) . (pt <- 4)) ; Switch(N, C, (pt = 2) . (pt <- 4)) + (C ? (pt = 12) . (pt <- 14)) ; Switch(N, C, (pt = 12) . (pt <- 14)) + (C ? zero) ; Switch(N, C, zero) + (C ? (pt = 6) . (pt <- 7)) ; Switch(N, C, (pt = 6) . (pt <- 7)) + (C ? (pt = 8) . (pt <- 10)) ; Switch(N, C, (pt = 8) . (pt <- 10))) .

	
	---rl [sw-1] : Switch(N, C, P) => P ; Switch(N, C, P) + (C ? (pt = 2) . (pt <- 4)) ; Switch(N, C, (pt = 2) . (pt <- 4)) .
	---rl [sw-2] : Switch(N, C, P) => P ; Switch(N, C, P) + (C ? (pt = 12) . (pt <- 14)) ; Switch(N, C, (pt = 12) . (pt <- 14)) .
	---rl [sw-3] : Switch(N, C, P) => P ; Switch(N, C, P) + (C ? zero) ; Switch(N, C, zero) .
	---rl [sw-4] : Switch(N, C, P) => P ; Switch(N, C, P) + (C ? (pt = 6) . (pt <- 7)) ; Switch(N, C, (pt = 6) . (pt <- 7)) .
	---rl [sw-5] : Switch(N, C, P) => P ; Switch(N, C, P) + (C ? (pt = 8) . (pt <- 10)) ; Switch(N, C, (pt = 8) . (pt <- 10)) .
	



	---D .= (Switch(1, 1 : upS1, pt = 2 . pt <- 4) || Switch(2, 2 : upS2, pt = 12 . pt <- 14) || Switch(3, 3 : upS3, zero) || Switch(4, 4 : upS4, zero) || Switch(5, 5 : upS5, pt = 6 . pt <- 7) || Switch(6, 6 : upS6, pt = 8 . pt <- 10)) . 

	---(L .= (((pt = 3) . (pt <- 5)) + ((pt = 4) . (pt <- 6)) + ((pt = 7) . (pt <- 8)) + ((pt = 9) . (pt <- 11)) + ((pt = 10) . (pt <- 12))) ; L)

	---C1 .= ((1 : upS1 ! zero) || (3 : upS3 ! (pt = 1 . pt <- 3)) || (5 : upS5 ! (pt = 5 . pt <- 7)))
	---C2 .= ((2 : upS2 ! zero) || (4 : upS4 ! (pt = 11 . pt <- 13)) || (6 : upS6 ! (pt = 8 . pt <- 9)))

	---SDN .= D || C1 || C2 || L
	
	---in_label .= [E x #(id : N1, typ : N2, dst : N3, pt : 1, sw : N5) x insert(1, upS1, emptyCoMap), insert(2, upS2, emptyCoMap), insert(3, upS3, emptyCoMap), insert(4, upS4, emptyCoMap), insert(5, upS6, emptyCoMap), insert(6, upS6, emptyCoMap) x Ne x R]
	---out_label .= [E' x #(id : N1', typ : N2', dst : N3', pt : 14, sw : N5') x Co' x Ne' x R']

	---search [, 3] < ((Switch(1, 1 : upS1, pt = 2 . pt <- 4) || Switch(2, 2 : upS2, pt = 12 . pt <- 14) || Switch(3, 3 : upS3, zero) || Switch(4, 4 : upS4, zero) || Switch(5, 5 : upS5, pt = 6 . pt <- 7) || Switch(6, 6 : upS6, pt = 8 . pt <- 10)) || ((1 : upS1 ! zero) || (3 : upS3 ! (pt = 1 . pt <- 3)) || (5 : upS5 ! (pt = 5 . pt <- 7))) || ((2 : upS2 ! zero) || (4 : upS4 ! (pt = 11 . pt <- 13)) || (6 : upS6 ! (pt = 8 . pt <- 9))) || (L .= (((pt = 3) . (pt <- 5)) + ((pt = 4) . (pt <- 6)) + ((pt = 7) . (pt <- 8)) + ((pt = 9) . (pt <- 11)) + ((pt = 10) . (pt <- 12))) ; L)), [E x #(id : N1, typ : N2, dst : N3, pt : 2, sw : N5) x insert(1, upS1, emptyCoMap), insert(2, upS2, emptyCoMap), insert(3, upS3, emptyCoMap), insert(4, upS4, emptyCoMap), insert(5, upS6, emptyCoMap), insert(6, upS6, emptyCoMap) x Ne x R] > =>* < P, [E' x #(id : N1', typ : N2', dst : N3', pt : 13, sw : N5') x Co' x Ne' x R'] > .

	---search < Switch(1, 1 : upS1, pt = 2 . pt <- 4), [E x #(id : N1, typ : N2, dst : N3, pt : 2, sw : N5) x insert(1, upS1, emptyCoMap) x Ne x R] > =>* < P', [E' x #(id : N1', typ : N2', dst : N3', pt : 4, sw : N5') x Co' x Ne' x R'] > . 
	---search < pre-terminate . pt <- 4, [E x #(id : N1, typ : N2, dst : N3, pt : 2, sw : N5) x insert(1, upS1, emptyCoMap) x Ne x R] > =>* < P', [E' x #(id : N1', typ : N2', dst : N3', pt : 4, sw : N5') x Co' x Ne' x R'] > . 

endm